spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: xfooddb
      username: root
      password: secret
  application:
    name: xfood-api
  profiles:
    active: dev

server:
  port: 8080

logging:
  level:
    root: INFO